endpoints:
  restart:
    enabled: true
  metrics:
    enabled: true
    sensitive: false
    
spring:
  application:
    name: play-service
  activemq:
    broker-url: tcp://broker-amq-tcp:61616
    user: admin
    password: admin